export const evalElements = [
  {
    id: 1,
    name: '주거학종합설계',
    prof: '전남일',
    semester: '2021 제1학기',
    book: '없음',
    assign: '有',
    teamplay: '有',
    grade: '3',
    attendance: '直接點名',
    test: '1號',
    score: '5分',
    review:
      '이것은 건축군 설계에 관한 수업입니다.팀워크와 전문성을 강화해 주는 등 도움이 많이 됩니다.',
  },
  {
    id: 2,
    name: '한국어사',
    prof: '배주채',
    semester: '8',
    book: '한국어사',
    assign: '有',
    teamplay: '無',
    grade: '3',
    attendance: '電子出勤',
    test: '1號',
    score: '3分',
    review: '好',
  },
];
